# Contenu éditorial de la refonte (source : docs/arborescence.md + docs/recadrage.md)

PILLARS = [
    dict(
        slug="acquisition", num="01", verb="Attirer", name="Acquisition",
        tagline="Trouvez et captez vos prochains clients.",
        title="Trouvez les bonnes personnes.",
        lead="Prospection, pages, codes QR et campagnes : Vivoo repère vos prochains clients et les fait entrer dans votre système dès le premier contact, avec leur source et leur contexte.",
        chips=["Prospection", "Pages", "Codes QR", "Campagnes", "CAPI"],
        items=[
            ("Prospection", "Repérez les entreprises qui correspondent à votre client idéal, directement à partir de Google Maps, et ajoutez-les à votre audience.", "/produit/prospection/"),
            ("Pages de capture", "Une page simple, à votre image, qui transforme un visiteur en contact identifié, prêt à être engagé.", "/produit/capture/"),
            ("Codes QR", "En boutique, sur une facture ou à un événement : un scan suffit pour rejoindre votre audience, sans application à installer.", "/produit/capture/"),
            ("Campagnes", "Diffusez une offre ou une invitation sur le canal que vos futurs clients utilisent déjà.", "/produit/campagnes/"),
            ("Mesure Meta (Pixel et CAPI)", "Chaque capture, rendez-vous ou achat est renvoyé à Meta pour que vos publicités ciblent mieux la fois suivante.", None),
        ],
        method=[
            ("Repérer", "Définissez votre client idéal et vos points d'entrée : annonces, pages, codes QR, prospection."),
            ("Capter", "Un formulaire, un scan ou un premier message suffit : le contact est créé dans Vivoo."),
            ("Qualifier", "Source, intérêt, étiquettes : chaque contact arrive avec le contexte qui permet de bien lui répondre."),
            ("Mesurer", "Les conversions remontent à Meta et affinent le ciblage de vos prochaines campagnes."),
        ],
        gets=["Une source identifiée pour chaque contact", "Des points de capture en ligne et sur place", "Des contacts prêts à être engagés", "Des publicités mieux ciblées, au fil des conversions"],
        scenario=("publicite", "Transformer une publicité en client"),
    ),
    dict(
        slug="conversation", num="02", verb="Converser", name="Conversation",
        tagline="Transformez chaque échange en opportunité.",
        title="Ne perdez plus le fil d'une conversation.",
        lead="WhatsApp, Instagram, Messenger, courriel et SMS arrivent au même endroit et s'ajoutent au même profil. Vous répondez plus vite, et plus rien ne dépend de votre mémoire.",
        chips=["WhatsApp", "Instagram", "Messenger", "Courriel", "SMS", "CRM"],
        items=[
            ("WhatsApp", "Répondez, relancez et automatisez sur le canal que vos clients ouvrent le plus.", None),
            ("Instagram", "Messages directs et échanges issus de vos publications, dans la même boîte de réception.", None),
            ("Messenger", "Les conversations de votre page Facebook, sans changer d'outil.", None),
            ("Courriel", "Pour les confirmations, les messages plus longs et les infolettres.", None),
            ("SMS", "Pour les rappels et les messages qui doivent être lus rapidement.", None),
            ("CRM et audience unifiée", "Chaque échange s'ajoute à un profil unique, peu importe le canal utilisé.", "/produit/audience-unifiee/"),
        ],
        method=[
            ("Recevoir", "Tous les messages, de tous les canaux, arrivent dans une seule boîte de réception."),
            ("Reconnaître", "Vivoo rattache chaque message au bon profil, avec son historique complet."),
            ("Répondre", "Vous ou votre équipe répondez ; une réponse automatique peut prendre le relais."),
            ("Faire avancer", "Une étiquette, un lien de réservation, une offre : la conversation devient une étape du parcours."),
        ],
        gets=["Une boîte de réception pour tous vos canaux", "Un historique complet pour chaque client", "Des conversations partagées dans l'équipe", "Aucune demande oubliée"],
        scenario=("conversation", "Convertir une conversation"),
    ),
    dict(
        slug="conversion", num="03", verb="Convertir", name="Conversion",
        tagline="Passez de l'intérêt à l'action.",
        title="Transformez l'intérêt en action.",
        lead="Un rendez-vous, une inscription, un paiement : Vivoo place la bonne action au bon moment du parcours, puis s'occupe des confirmations et des rappels.",
        chips=["Rendez-vous", "Pages de conversion", "Pages de vente", "Paiement"],
        items=[
            ("Rendez-vous", "Un calendrier en ligne synchronisé avec Google Agenda, avec confirmations et rappels automatiques.", "/produit/rendez-vous/"),
            ("Pages de conversion", "Une page pensée pour une seule action : réserver, s'inscrire ou demander une soumission.", None),
            ("Pages de vente", "Présentez une offre, un produit ou un service et laissez le client passer à l'achat.", None),
            ("Paiement", "Le client paie en ligne et la transaction s'ajoute à son profil.", None),
        ],
        method=[
            ("Proposer", "Le bon lien, au bon moment de la conversation ou de la campagne."),
            ("Engager", "Réservation, inscription ou achat en quelques clics, sans aller-retour."),
            ("Confirmer", "Confirmation et rappels partent automatiquement sur le canal du client."),
            ("Enregistrer", "Le rendez-vous ou la vente s'ajoute au profil et déclenche l'étape suivante."),
        ],
        gets=["Un agenda qui se remplit sans allers-retours", "Moins de rendez-vous manqués grâce aux rappels", "Des pages qui mènent à une action claire", "Chaque conversion reliée à son origine"],
        scenario=("agenda", "Remplir son agenda"),
    ),
    dict(
        slug="vente", num="04", verb="Vendre", name="Vente",
        tagline="De la commande à la relation client.",
        title="De la commande à la relation client.",
        lead="Produits, services, commandes et événements : Vivoo suit la vente jusqu'au bout, et c'est justement là que commence la relation suivante.",
        chips=["Produits", "Services", "Ventes", "Commandes", "Événements"],
        items=[
            ("Produits et services", "Votre catalogue dans Vivoo, prêt à être proposé dans une page ou dans une conversation.", None),
            ("Ventes et commandes", "Suivez chaque commande de la préparation à la livraison, et tenez le client informé.", None),
            ("Commerce connecté", "Synchronisez vos ventes Shopify, Square, Clover ou WooCommerce avec vos profils clients.", "/produit/commerce/"),
            ("Événements", "Inscriptions, billets et communication avant, pendant et après l'événement.", "/produit/evenements/"),
        ],
        chain=["Page de vente", "Paiement", "Vente", "Commande", "Préparation et expédition", "Livraison", "Avis", "Fidélisation"],
        gets=["Vos ventes en ligne et en boutique réunies", "Un suivi de commande visible pour le client", "Un historique d'achat pour chaque profil", "Un avis demandé après chaque livraison"],
        scenario=("vente", "Transformer une vente en relation durable"),
    ),
    dict(
        slug="fidelisation", num="05", verb="Fidéliser", name="Fidélisation",
        tagline="Faites revenir vos clients.",
        title="Un client ne devrait pas être une vente unique.",
        lead="Campagnes, promotions, points et avis : Vivoo reconnaît vos clients, les récompense et les fait revenir au bon moment, sans que la relance dépende d'y penser.",
        chips=["Campagnes", "Promotions", "Codes promo", "Fidélité", "Avis", "RFM"],
        items=[
            ("Campagnes", "Des messages ciblés selon l'historique de chaque client, sur le canal qu'il préfère.", "/produit/campagnes/"),
            ("Promotions et codes promo", "Créez une offre, partagez-la, et voyez qui l'utilise vraiment.", None),
            ("Programme de fidélité", "Des points proportionnels aux achats et des paliers de récompenses.", "/produit/fidelisation/"),
            ("Avis et réputation", "Demandez un avis au bon moment et gardez un œil sur votre réputation.", "/produit/reputation/"),
            ("Segmentation RFM", "Récence, fréquence, montant : repérez vos meilleurs clients et ceux qui s'éloignent.", None),
        ],
        method=[
            ("Reconnaître", "Chaque client est identifié, avec son historique d'achat et d'échanges."),
            ("Récompenser", "Points, paliers et offres réservées : la fidélité devient visible."),
            ("Réactiver", "Un client silencieux depuis trop longtemps reçoit le bon message, au bon moment."),
            ("Faire recommander", "Les clients satisfaits laissent un avis et deviennent votre meilleure acquisition."),
        ],
        gets=["Des clients qui reviennent plus souvent", "Des relances qui partent toutes seules", "Une vue claire de vos meilleurs clients", "Plus d'avis, au bon moment"],
        scenario=("inactif", "Faire revenir un client inactif"),
    ),
    dict(
        slug="automatisation", num="06", verb="Automatiser", name="Automatisation",
        tagline="Laissez Vivoo prendre en charge ce qui se répète.",
        title="Faites travailler le système.",
        lead="Ce qui se répète ne devrait plus dépendre de vous. Vivoo déclenche les bonnes actions au bon moment, et vous garde informé quand une intervention humaine compte vraiment.",
        chips=["Automatisations", "Séquences", "Notifications", "Déclencheurs"],
        items=[
            ("Déclencheurs", "Un scan, un achat, un mot-clé, une date, un rendez-vous ou une période d'inactivité.", None),
            ("Automatisations", "Une action part toute seule dès que le déclencheur se produit.", "/produit/automatisation/"),
            ("Séquences", "Plusieurs messages s'enchaînent dans le temps, et s'arrêtent dès que le client répond ou achète.", "/produit/automatisation/"),
            ("Notifications", "Vous et votre équipe êtes avertis quand une action humaine est nécessaire.", None),
        ],
        gets=["Moins de tâches répétitives", "Des relances qui ne s'oublient plus", "Un parcours qui avance même quand vous êtes occupé", "Une équipe avertie au bon moment"],
        scenario=("publicite", "Voir un parcours complet"),
    ),
]

SECTORS = [
    dict(
        slug="therapeutes", name="Thérapeutes", offer="Alma",
        who="Massothérapeutes, naturopathes, ostéopathes, psychothérapeutes, coachs et praticiens en soins.",
        title="Plus de temps pour vos clients. Moins de temps à chercher les prochains.",
        short="Prospecter → RDV → suivi → fidélisation",
        flow=["Prospection", "Conversation", "Rendez-vous", "Consultation", "Avis", "Fidélisation"],
        pains=[
            ("Un agenda qui se remplit seul", "Vos clients réservent en ligne, reçoivent leurs rappels et vous évitez les allers-retours par message."),
            ("Un suivi qui ne dépend pas de votre mémoire", "Après la séance, un message de suivi puis une invitation à reprendre rendez-vous partent au bon moment."),
            ("Une réputation qui se construit", "Un avis est demandé après chaque consultation, quand la satisfaction est encore fraîche."),
        ],
        pillars=["acquisition", "conversation", "conversion", "fidelisation"],
        offer_text="Alma est l'offre Vivoo préconfigurée pour les thérapeutes : les modules, les pages et les scénarios dont une pratique a besoin, déjà en place.",
        case=("Kinaya Massothérapeute", "Gatineau", "Une page de capture accueille les nouveaux clients dès leur premier contact, et le calendrier intégré permet une prise de rendez-vous autonome. Résultat : moins d'administration, plus de temps pour la pratique."),
    ),
    dict(
        slug="restaurants", name="Restaurants et commerces alimentaires", offer="Zagor",
        who="Restaurants, cafés, boulangeries, épiceries et traiteurs.",
        title="Faites revenir vos clients, pas seulement leurs commandes.",
        short="QR → client → offre → fidélité → retour",
        flow=["Code QR", "Contact", "Promotion", "Visite", "Fidélité", "Retour"],
        pains=[
            ("Des clients enfin identifiés", "Un code QR sur la table ou à la caisse transforme un client de passage en contact que vous pouvez recontacter."),
            ("Des promotions qui ramènent du monde", "Une offre ciblée un mardi tranquille, sur WhatsApp ou par SMS, pour les clients qui ne sont pas venus depuis un moment."),
            ("Une fidélité qui se voit", "Des points à chaque visite et des récompenses qui donnent une raison de revenir."),
        ],
        pillars=["acquisition", "fidelisation", "automatisation"],
        offer_text="Zagor est l'offre Vivoo préconfigurée pour la restauration : capture par code QR, programme de fidélité et campagnes de retour, prêts à l'emploi.",
        case=("MakoFoods", "Restaurant et épicerie, Longueuil", "Une page de capture affichée en caisse et sur les tables permet à chaque client de rejoindre l'audience. Chaque achat, côté restaurant ou épicerie, nourrit le même profil, et les campagnes réactivent les clients moins fréquents."),
    ),
    dict(
        slug="commerce", name="Commerce", offer="",
        who="Boutiques, commerces en ligne, grossistes et commerces de proximité.",
        title="Transformez chaque visite en relation.",
        short="Prospect → vente → commande → avis → fidélisation",
        flow=["Capture", "Vente", "Commande", "Avis", "Fidélisation"],
        pains=[
            ("Des ventes reliées à des personnes", "Vos ventes en ligne et en boutique s'ajoutent au profil de chaque client, avec Shopify, Square, Clover ou WooCommerce."),
            ("Une commande suivie jusqu'au bout", "Confirmation, préparation, livraison : le client est informé à chaque étape, sur son canal."),
            ("Un prochain achat préparé", "Avis, points et offres personnalisées transforment un premier achat en habitude."),
        ],
        pillars=["acquisition", "vente", "fidelisation"],
        offer_text="",
        case=("Twish Cart", "Épicerie en gros, Ottawa", "La page de capture recrute de nouveaux comptes, le module de rendez-vous organise les suivis et livraisons, la fidélisation récompense les achats récurrents et les campagnes font connaître chaque nouvel arrivage."),
    ),
    dict(
        slug="services", name="Services", offer="",
        who="Entrepreneurs en services, consultants, agences, métiers et services à domicile.",
        title="De la demande au client fidèle.",
        short="Acquisition → qualification → RDV → vente",
        flow=["Prospection", "Qualification", "Rendez-vous", "Vente", "Relance"],
        pains=[
            ("Des demandes qualifiées avant l'appel", "Quelques questions automatiques suffisent pour savoir qui vous écrit et ce dont il a besoin."),
            ("Des rendez-vous sans friction", "Le prospect qualifié réserve directement un créneau dans votre agenda."),
            ("Des soumissions qui ne dorment plus", "Une séquence de relance part d'elle-même tant que la soumission n'a pas de réponse."),
        ],
        pillars=["acquisition", "conversation", "conversion", "automatisation"],
        offer_text="",
        case=None,
    ),
    dict(
        slug="evenements", name="Événements", offer="",
        who="Organisateurs, salles, festivals, formations et conférences.",
        title="Avant, pendant et après l'événement.",
        short="Inscription → communication → vente → présence → suivi",
        flow=["Inscription", "Communication", "Vente", "Présence", "Suivi", "Fidélisation"],
        pains=[
            ("Des inscriptions centralisées", "Chaque participant rejoint votre audience, avec son canal préféré et son historique."),
            ("Une communication qui se déroule toute seule", "Confirmation, rappels, informations pratiques : la séquence part au bon moment."),
            ("Un public qui revient", "Après l'événement, un message de remerciement, une demande d'avis et une invitation au prochain."),
        ],
        pillars=["acquisition", "vente", "automatisation", "fidelisation"],
        offer_text="",
        case=None,
    ),
]

SCENARIOS = [
    dict(
        id="publicite", desc="De l'annonce Meta au rendez-vous, sans perdre le prospect en route.", home="Acquérir un prospect", title="Transformer une publicité en client",
        text="Une personne voit votre publicité, arrive sur une page, laisse ses coordonnées et poursuit l'échange sur WhatsApp. Quelques questions suffisent pour la qualifier, puis elle réserve un rendez-vous qui mène à la vente.",
        steps=[("Publicité", "Une annonce Meta, avec un objectif clair"), ("Page", "Une page de capture à votre image"), ("Capture", "Le contact est créé avec sa source"), ("WhatsApp", "La conversation démarre sur son canal"), ("Qualification", "Quelques questions automatiques"), ("Rendez-vous", "Réservé directement dans votre agenda"), ("Vente", "Enregistrée dans son profil")],
        pillars=["Acquisition", "Conversation", "Conversion"],
    ),
    dict(
        id="conversation", desc="Un message du dimanche soir devient une opportunité lundi matin.", home="Convertir une conversation", title="Convertir une conversation",
        text="Un message arrive un dimanche soir. Vivoo répond aussitôt, pose les bonnes questions et propose le lien de réservation ou de paiement. Lundi matin, l'opportunité vous attend, déjà avancée.",
        steps=[("Message entrant", "WhatsApp, Instagram ou Messenger"), ("Réponse immédiate", "Même en dehors de vos heures"), ("Qualification", "Besoin, budget, délai"), ("Proposition", "Un lien de réservation ou de paiement"), ("Rendez-vous ou achat", "L'action est posée"), ("Suivi", "Votre équipe reprend la main au bon moment")],
        pillars=["Conversation", "Conversion", "Automatisation"],
    ),
    dict(
        id="agenda", desc="Des prospects qualifiés qui réservent eux-mêmes, et se présentent.", home="Remplir son agenda", title="Remplir son agenda",
        text="Vivoo repère des prospects, engage la conversation et les amène jusqu'au rendez-vous. Le rappel limite les absences, et l'avis demandé après la séance nourrit votre réputation.",
        steps=[("Prospection", "Des entreprises ou des personnes qui vous correspondent"), ("Conversation", "Un premier échange personnalisé"), ("Qualification", "Le besoin est confirmé"), ("Rendez-vous", "Réservé en ligne"), ("Rappel", "La veille, sur son canal"), ("Avis", "Demandé après la séance")],
        pillars=["Acquisition", "Conversion", "Fidélisation"],
    ),
    dict(
        id="vente", desc="La vente prépare l'avis, la fidélité et la vente suivante.", home="Vendre", title="Transformer une vente en relation durable",
        text="La vente n'est pas la fin du parcours. Vivoo suit la commande jusqu'à la livraison, demande un avis, attribue des points, puis propose le bon produit au bon moment.",
        steps=[("Vente", "En ligne ou en boutique"), ("Commande", "Confirmée automatiquement"), ("Livraison", "Le client est informé à chaque étape"), ("Avis", "Demandé après réception"), ("Fidélisation", "Des points et une offre réservée"), ("Nouvelle vente", "Le parcours recommence")],
        pillars=["Vente", "Fidélisation"],
    ),
    dict(
        id="inactif", desc="Après 30 jours de silence, le bon message part tout seul.", home="Relancer", title="Faire revenir un client inactif",
        text="Un client achetait régulièrement, puis plus rien. Après trente jours, Vivoo le détecte et lui envoie un message personnalisé avec une offre. Vous le voyez revenir, sans avoir eu à y penser.",
        steps=[("Achat", "Le dernier achat est enregistré"), ("30 jours", "Aucune nouvelle activité"), ("Détection", "Le client passe en « à réactiver »"), ("Message", "Personnalisé, sur son canal préféré"), ("Offre", "Une raison concrète de revenir"), ("Nouvel achat", "Le compteur repart à zéro")],
        pillars=["Fidélisation", "Automatisation"],
    ),
    dict(
        id="qr", desc="Un client de passage devient un habitué.", home="Fidéliser", title="Transformer un code QR en client fidèle",
        text="Un client scanne le code QR sur sa table. Il reçoit une offre de bienvenue, revient, cumule des points et reçoit une relance quand il se fait plus rare. Un client de passage devient un habitué.",
        steps=[("Code QR", "Sur la table, à la caisse ou sur la facture"), ("Capture", "Sans application à installer"), ("Offre", "Un mot de bienvenue et une raison de revenir"), ("Visite", "Il revient"), ("Achat", "Enregistré dans son profil"), ("Points", "Sa fidélité devient visible"), ("Relance", "Au bon moment, s'il se fait rare")],
        pillars=["Acquisition", "Fidélisation", "Automatisation"],
    ),
]
